### ISSUE TITLE
site not linking properly / lab menu not showing / Lab1 not updating

### ISSUE THREAD

**Issue by plzmsu** [SpaCE-Lab-MSU/MSUGradSpatialEcology#8]
Hi @billspat 
I teach my lab tomorrow @ 2:10pm and thought the lab website was updating ok. I was able to get the index to update, but I can’t even get the banner on top (Lab1, Lab2, etc.) to show up, nor can I navigate to Lab1 or Lab2, etc. pages. 

I’ve updated the index and Lab1.Rmd files, knitted them, and then did “rmarkdown::render_site()”. This seemed to work but included lots and lots of small files I didn’t recognize showing up as new ones to commit. Note that I used "rmarkdown::" instead of "markdown:: " which didn't seem to wokr.

I only selected Lab1 and index files to commit and push. The index shows up online here: [https://space-lab-msu.github.io/MSUGradSpatialEcology/index.html] but the lab1 I can’t get to.

Any ideas before 2pm? Otherwise I'll just post the PDF and Rmd for Lab 1 on D2L.

**Comment by billspat** [comment]
The HTML rendered has the menu and links in it, so that seems correct.  Without seeing all the small files you mention I have to guess, but they may be the support files : css and javascript that make the menu work for the theme ( specifically the bootstrap library that makes the menu work ).    Those css/javascript libraries may need to be updated, and Pandoc is doing that automatically.  

You could create a new branch from the current state , maybe called "FS22" , and commit and push all those small files so I can see.    Or just push all the small files to main branch all to see what happens, knowing that with git you can reset to an earlier commit if necessary.

**Comment by plzmsu** [comment]
It seems like it's working now for some reason. I didn't do any edits.

**Comment by billspat** [comment]
it's still not working.   For the pages you updates (index and lab1 ) the menu bar overhangs the header, and the mobile menu (the three bars) doesn't open. those pages are also throwing errors (in the code inspector) about support librarya issues (bootstrap css theme and javascript), futher supporting my suggestion above.    The other pages that you didn't edit (lab 2, etc) it all works, because they are still pointing to the old css/javascript libraries that are on the site.   If you push everything that may fix it.  You must also push all of the lab pages that you have not updated to content of (e.g. lab 2, lab 3, etc) because after you update the css/javascript libraries on the site, those pages will also be changed (in the invisible html code section, pointing to the new libs).

**Comment by plzmsu** [comment]
@billspat I'm updating one lab at a time, I updated lab 4 but it seems to be stuck on the push. I reverted to the Lab2 commit first because I accidentally editing lab4 files in /docs/ - I undid this, but now lab4 files including Rmd and html are not pushing. It seems to be hung up. Any ideas? Do I need to build the site over?

**Comment by plzmsu** [comment]
Reset it several times (reversed commits) and finally worked.

**Comment by plzmsu** [comment]
Hi Pat- I teach most of the time until my lab so I probably won’t get to this. If you’re able to fork it and try, great but otherwise I will just provide the PDF and Rmd.

On Sep 7, 2022, at 7:11 AM, Pat Bills ***@***.***> wrote:

﻿

The HTML rendered has the menu and links in it, so that seems correct. Without seeing all the small files you mention I have to guess, but they may be the support files : css and javascript that make the menu work for the theme ( specifically the bootstrap library that makes the menu work ). Those css/javascript libraries may need to be updated, and Pandoc is doing that automatically.

You could create a new branch from the current state , maybe called "FS22" , and commit and push all those small files so I can see. Or just push all the small files to main branch all to see what happens, knowing that with git you can reset to an earlier commit if necessary.
